-- General Icons
return {
	loading = "􀖇",
	apple = "􀣺",
	preferences = "􀺽",
	activity = "􀒓",
	lock = "􀒳",
	bell = "􀋚",
	bell_dot = "􀝗",
	music = "􀑪",

	-- git icons,
	git_issue = "􀍷",
	git_discussion = "􀒤",
	git_pull_request = "􀙡",
	git_commit = "􀡚",
	git_indicator = "􀂓",

	-- spotify icons,
	spotify_back = "􀊎",
	spotify_play_pause = "􀊈",
	spotify_next = "􀊐",
	spotify_shuffle = "􀊝",
	spotify_repeat = "􀊞",

	-- yabai icons,
	yabai_stack = "􀏭",
	yabai_fullscreen_zoom = "􀂓",
	yabai_parent_zoom = "􀥃",
	yabai_float = "􀢌",
	yabai_grid = "􀧍",
	yabai_split_vertical = "􀘜",
	yabai_split_horizontal = "􀧋",

	-- battery icons,
	battery = {
		_100 = "􀛨",
		_75 = "􀺸",
		_50 = "􀺶",
		_25 = "􀛩",
		_0 = "􀛪",
		charging = "􀢋",
	},

	-- volume icons,
	volume_100 = "􀊩",
	volume_66 = "􀊧",
	volume_33 = "􀊥",
	volume_10 = "􀊡",
	volume_0 = "􀊣",
}
